# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/shinoyom89@gmail.com/News_dlt_pipeline")

# COMMAND ----------

# DBTITLE 1,Cell 3
# MAGIC %sql
# MAGIC
# MAGIC
# MAGIC FROM crypto_dlt.source.crypto_raw coins
# MAGIC ORDER BY last_updated DESC 
# MAGIC LIMIT 20

# COMMAND ----------


