# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/shinoyom89@gmail.com/New Pipeline 2026-03-27 17:21")

# COMMAND ----------

spark.read.table("dlt_catalog.source.customers").display()

# COMMAND ----------


